CHANGELOG.rst
src/lipyphilic/lib/neighbours.py
tests/lipyphilic/lib/test_neighbours.py

Fixes #11 
- Allow non-sequential residue indices in neighbour calculation
- This is done using `scipy.stats.rankdata` to sort the residue indices
- Add a test that previously failed but now passes
PR Checklist
------------

Allow non-sequential residue indices in neighbour calculation

---

src/lipyphilic/lib/area_per_lipid.py
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/flip_flop.py
src/lipyphilic/lib/neighbours.py
src/lipyphilic/lib/registration.py

- All analysis classes now use `super` upon initialisation

Initialise analysis subclasses with super

---

AUTHORS.rst
CHANGELOG.rst
docs/reference/analyses.rst
docs/reference/lib/order_parameter.rst
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/order_parameter.py
tests/lipyphilic/lib/test_assign_leaflets.py
tests/lipyphilic/lib/test_order_parameter.py

Fixes #23 
- Added a tool to calculate the coarse-grained order parameter of lipids in a bilayer
- Local membrane normals that define the molecular axes can be passed to the class 
- The tool calculates the Scc for **one tail at a time** - the atom selection should cover only the *sn1* tail **or** the *sn2* tail, not both.
- There is a static method that takes two SCC objects then calculates the weighted-average SCC for each lipid at each frame. The weights are defined by the number of beads in each tail of a lipid.
PR Checklist
------------

Scc analysis tool

---

.gitignore
README.rst
docs/reference/analyses.rst
src/lipyphilic/lib/order_parameter.py
src/lipyphilic/lib/plotting.py
tests/lipyphilic/lib/test_order_parameter.py
tests/lipyphilic/lib/test_plotting.py

- Added a class `ProjectionPlot` to plot projections of membrane properties (e.g. area per lipid, lipid order parameter) onto the 2D membrane plane
- Uses `matplotlib.pyplot.imshow` for plotting
- Added a method `project_SCC` to to `lipyphilic.lib.order_parameters.SCC` that calculates time-averaged order parameters for each lipid and projects this onto the membrane plane using `ProjectionPlot`
- Modified `lipyphilic.lib.order_parameters.SCC.weighted_average` to return a new `SCC` object rather than a NumPy array. This allows using `project_SCC` with the averaged order parameters.
- Added tests for the new class and method
- Updated docs
PR Checklist
------------

Plotting projections of membrane properties

---

CHANGELOG.rst
src/lipyphilic/lib/z_thickness.py
tests/lipyphilic/lib/test_z_thickness.py

- ZThickness.average() returns a new ZThickness object rather than a NumPy array
- This is now in keeping with SCC.weighted_average() returning a new SCC object
- Updated tests to reflect a ZThickness object is returned, and the results are stored in a NumPy array in the .z_thickness attribute.
PR Checklist
------------

ZThickness.average() returns a new ZThickness object

---

CHANGELOG.rst
src/lipyphilic/lib/area_per_lipid.py
src/lipyphilic/lib/order_parameter.py
tests/lipyphilic/lib/test_area_per_lipid.py

Fixes #33 
- Wrapper around `lipyphilic.lib.plotting.ProjectionPlot` to simplify projecting the area per lipid onto the membrane plane
PR Checklist
------------

Project area onto membrane plane

---

CHANGELOG.rst
src/lipyphilic/lib/neighbours.py
src/lipyphilic/lib/z_positions.py
src/lipyphilic/transformations.py

- Add progress bar to `lipyphilic.lib.Neighbours.largest_cluster`
- Fix typos in docstrings
- Add `min_diff` argument to `lipyphilic.transformations.center_membrane`. This sets the minimum difference required between the peak-to-peak distance of a membrane and the box length in order for the membrane to be considered whole.

Minor fixes

---

CHANGELOG.rst
src/lipyphilic/lib/neighbours.py
tests/lipyphilic/lib/test_neighbours.py

Fixes #51 
- `lipyphilic.lib.neighbours.Neighbours` now stores results as a NumPy array of SciPy csc matrices
- For large systems/trajectories, this becomes significantly faster than using a single list-of-lists matrix for the entire analysis
- Test and documentation updated to reflect the change in format of the results
PR Checklist
------------

Improve performance of lipyphilic.lib.neighbours.Neighbours

---

CHANGELOG.rst
src/lipyphilic/lib/flip_flop.py

- Inside `FlipFlop._setup_frames`, `FlipFlop.frames` is now created using `np.arange` rather than by iterating over the trajectory
- For long trajectories this provides a large performance boost
PR Checklist
------------

Improve FlipFLop performance

---

CHANGELOG.rst
src/lipyphilic/lib/order_parameter.py

- Fixed typos in `lipyphilic.lib.order_parameter` docs

Typos in docs

---

CHANGELOG.rst
src/lipyphilic/lib/order_parameter.py
tests/lipyphilic/lib/test_order_parameter.py

- Previously, `lipyphilic.lib.order_parameter.SCC.weighted_average` would fail if the sn1 and sn2 `SCC` objects had differing numbers of lipids
- This has now been fixed and a test added that would previously fail but now passes
PR Checklis
------------

Scc weighted average

---

CHANGELOG.rst
src/lipyphilic/lib/assign_leaflets.py

* Both `AssignLeaflets` and `AssignCurvedLeaflets` now inherit from a shared base class (`AssignLeafletsBase`)
* Eventually, there should be a single `AssignLeaflets` class that will switch between using either the current `AssignLeaflets` approach or the `AssignCurvedLeaflets` approach depending on the arguments passed.
PR Checklist
------------

Add abstact base class for leaflet analysis

---

CHANGELOG.rst
src/lipyphilic/lib/lateral_diffusion.py
src/lipyphilic/transformations.py
tests/lipyphilic/lib/test_lateral_diffusion.py

- `lipyphilic.lib.lateral_diffusion.msd.lagtimes` are now in ns rather than ps
- typos fixed in docstrings and comments
- fixed `lipyphilic.transformations.nojump` - the unwrapping was incorrect for the first frame. The check `dx < length_x/2` should be `dx < -length_x/2`
PR Checklist
------------

Change lagtimes from ps to ns

---

CHANGELOG.rst
README.rst
docs/reference/analyses.rst
src/lipyphilic/_simple_systems/pdbs/Triclinic-2Atoms.pdb
src/lipyphilic/_simple_systems/pdbs/Triclinic-3Atoms.pdb
src/lipyphilic/_simple_systems/simple_systems.py
src/lipyphilic/lib/area_per_lipid.py
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/memb_thickness.py
src/lipyphilic/lib/registration.py
src/lipyphilic/lib/z_angles.py
src/lipyphilic/lib/z_positions.py
src/lipyphilic/lib/z_thickness.py
src/lipyphilic/transformations.py
tests/lipyphilic/lib/test_area_per_lipid.py
tests/lipyphilic/lib/test_assign_leaflets.py
tests/lipyphilic/lib/test_memb_thickness.py
tests/lipyphilic/lib/test_registration.py
tests/lipyphilic/lib/test_z_angles.py
tests/lipyphilic/lib/test_z_positions.py
tests/lipyphilic/lib/test_z_thickness.py
tests/lipyphilic/test_transformations.py

Fixes #73 
- Some analyses in lipyphilic currently do not support triclinic systems
- An on-the-fly transfomation to convert triclinic coordinates to their orthorhombic representation has been added. This will be the recommended way to analyse triclinic systems.
Edit:
The on the fly transformation is equivalent to using `gmx trjconv` with the flag `-ur rect`.
PR Checklist
------------

Tri to ortho

---

src/lipyphilic/transformations.py

- Fixed the abruptly ending text in the docstring of `lipyphilic.transformations`

Fix missing text in docstring

---

src/lipyphilic/lib/order_parameter.py

Fixes #83 
- Add option to not unwrap lipids before projecting onto the xy plane
- `SCC.project_SCC` now takes an optional `unwrap` keyword
- To be consistent with previous behaviour, the default value of `unwrap` is `True`
PR Checklist
------------

Add option to not unwrap lipids before projecting onto the xy plane

---

.coveragerc
.github/workflows/ci.yml
CHANGELOG.rst
MANIFEST.in
pyproject.toml
requirements-dev.txt
requirements-dev.yml
src/lipyphilic/lib/plotting.py
tox.ini

Fixes #87 
- Added a workflow for testing, coverage checking, and building docs with github actions
- Updated `tox.ini` for use with github actions
- Using `tox-gh-actions` to run the tests
- Run tests on Python 3.7-3.9 on both Ubuntu and MacOS (Windows currently fails because it cannot build a wheel for freud-analysis)
- For Python 3.9 Ubuntu,  LiPyphilic is built, docs are built, flake is run, coverage is checked and uploaded to codecov
- Required to pass: tests with Python 3.9 (on both Ubuntu and MacOS), coverage of 100%
PR Checklist
------------

Switch from travis to github actions

---

src/lipyphilic/lib/plotting.py
tests/lipyphilic/lib/test_plotting.py

Fixes #84 
- If `norm` is present in the `imshow_kws` argument of either `ProjectionPlot.plot_projection` or `JointDensity.plot_density`, then the `vmin` and `vmax` arguments are not passed to `plt.imshow`. This is because an error is raised in matplotlib 3.5 if both `norm` and `vmin/vmax` are passed to `plt.imshow`
PR Checklist
------------

Norm keyowrd imshow

---

src/lipyphilic/lib/lateral_diffusion.py

- Use `attrs.define` along with type hints for the `MSD` analysis class.
- Use type hints for the `MSD.diffusion_coefficient` method
- Unnecessary `return None` statements removed 
PR Checklist
------------

Use attrs and type hints for the MSD analysis class

---

AUTHORS.rst
src/lipyphilic/analysis/memb_thickness.py

Fixes https://github.com/p-j-smith/lipyphilic/issues/100
The mean over the thickness matrix was assigned to self.memb_thickness_grid, which is not the expected behaviour
- self.memb_thickness_grid = difference in upper surface and lower surface matrices
PR Checklist
------------

Assign 2D histogram diff to memb_thickness_grid

---

src/lipyphilic/analysis/area_per_lipid.py
src/lipyphilic/analysis/flip_flop.py
src/lipyphilic/analysis/lateral_diffusion.py
src/lipyphilic/analysis/memb_thickness.py
src/lipyphilic/analysis/neighbours.py
src/lipyphilic/analysis/order_parameter.py
src/lipyphilic/analysis/registration.py
src/lipyphilic/analysis/z_angles.py
src/lipyphilic/analysis/z_positions.py
src/lipyphilic/analysis/z_thickness.py
src/lipyphilic/leaflets/assign_leaflets.py
tests/lipyphilic/lib/test_area_per_lipid.py
tests/lipyphilic/lib/test_assign_leaflets.py
tests/lipyphilic/lib/test_flip_flop.py
tests/lipyphilic/lib/test_lateral_diffusion.py
tests/lipyphilic/lib/test_memb_thickness.py
tests/lipyphilic/lib/test_neighbours.py
tests/lipyphilic/lib/test_order_parameter.py
tests/lipyphilic/lib/test_registration.py
tests/lipyphilic/lib/test_z_angles.py
tests/lipyphilic/lib/test_z_positions.py
tests/lipyphilic/lib/test_z_thickness.py

Fixes #60 
- use `mdanalysis.analysis.base.Results` for storing all results
- all results stored in the `.results` attribute
- all results can also be accessed via their original attributes (which are now properties)
PR Checklist
------------

Use the MDA `Results` class for storing analysis results

---

docs/reference/analyses.rst
docs/reference/tutorials.rst
src/lipyphilic/analysis/lateral_diffusion.py
src/lipyphilic/transformations/__init__.py
src/lipyphilic/transformations/transformations.py

Related to #105 
Related to #113 
- deprecate `lipyphilic.transformations.nojump`
- suggest use of `MDAnalysis.transformations.NoJump` instead
PR Checklist
------------

Deprecate `lipyphilic.transformations.nojump`

---

README.rst
docs/reference/analyses.rst
src/lipyphilic/analysis/area_per_lipid.py
src/lipyphilic/analysis/memb_thickness.py
src/lipyphilic/analysis/registration.py
src/lipyphilic/analysis/z_angles.py
src/lipyphilic/analysis/z_positions.py
src/lipyphilic/analysis/z_thickness.py
src/lipyphilic/leaflets/assign_leaflets.py
src/lipyphilic/transformations/__init__.py
src/lipyphilic/transformations/transformations.py
tests/lipyphilic/analysis/transformations/test_transformations.py
tests/lipyphilic/lib/test_area_per_lipid.py
tests/lipyphilic/lib/test_assign_leaflets.py
tests/lipyphilic/lib/test_memb_thickness.py
tests/lipyphilic/lib/test_registration.py
tests/lipyphilic/lib/test_z_angles.py
tests/lipyphilic/lib/test_z_positions.py
tests/lipyphilic/lib/test_z_thickness.py

- remove the `triclinic_to_orthorhombic` transformation - the distance between atoms changes after applying the transformation, and so results will be inaccurate
- raise an error if a triclinic system is used in an analysis/transformation that requires orthorhombic boxes
- remove mention of triclinic_to_orthorhombic from the docs
PR Checklist
------------

remove `triclinic_to_orthorhombic`

---

pyproject.toml
rust/Cargo.toml
rust/src/lib.rs
src/lipyphilic/__init__.py

- define the version in a single place (`rust/Cargo.toml`)]
- Also account for difference in specifying dev version between Rust and Python (`X.Y-dev0` vs `X.Y.dev0`)
PR Checklist
------------

Single source for package version

---

README.rst
pyproject.toml
src/lipyphilic/lib/area_per_lipid.py
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/flip_flop.py
src/lipyphilic/lib/lateral_diffusion.py
src/lipyphilic/lib/memb_thickness.py
src/lipyphilic/lib/neighbours.py
src/lipyphilic/lib/order_parameter.py
src/lipyphilic/lib/plotting.py
src/lipyphilic/lib/registration.py
src/lipyphilic/lib/z_angles.py
src/lipyphilic/lib/z_positions.py
src/lipyphilic/lib/z_thickness.py
src/lipyphilic/transformations/transformations.py

- Add deprecation warning to all classes that have moved or will be removed
- Remove warning from readme about breaking changes
- Pin `matplotlib < 3.8` due to [changes to `CounterSet`](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#contourset-is-now-a-single-collection)
PR Checklist
------------

Add deprecation warnings

---

src/lipyphilic/analysis/lateral_diffusion.py

- Rename`lipyphic.analysis.MSD` input parameter `u` to `universe`. This is the original name, it was accidentally changed at some point after the most recent release. Changing it back to avoid breaking changes
PR Checklist
------------

Rename MSD input parameter 'u' to 'universe'

---

pyproject.toml
src/lipyphilic/plotting/plotting.py
tests/lipyphilic/plotting/test_plotting.py

- unpin max matplotlib version
- don't pass `aspect` as a `cbar_kwarg` to `JointDensity.fig.colorbar` - it is ignored when creating the colorbar anyway
PR Checklist
------------

Remove requirement `matplotlib < 3.8`

---

src/lipyphilic/analysis/memb_thickness.py
src/lipyphilic/analysis/z_positions.py
src/lipyphilic/leaflets/assign_leaflets.py

Fixes #132
- always pass `x_bins` and `y_bins` to `scipy.stats.binned_statistic_2d` rather than assuming `x_bins == y_bins`
PR Checklist
------------

Handle the case where x and y dimensions are different when binning lipid `xy` positions

---

.github/workflows/publish.yml

- use `pypa/gh-action-pypi-publish` instead of `PyO3/maturin-action` for uploading to PyPI
PR Checklist
------------

use pypa/gh-action-pypi-publish instead of PyO3/maturin-action

---

AUTHORS.rst
CONTRIBUTING.rst
src/lipyphilic/analysis/area_per_lipid.py
src/lipyphilic/analysis/memb_thickness.py
src/lipyphilic/analysis/order_parameter.py
src/lipyphilic/analysis/z_positions.py
tests/lipyphilic/analysis/test_order_parameter.py
tests/lipyphilic/analysis/test_z_positions.py

- Fixes [#143](https://github.com/p-j-smith/lipyphilic/issues/143)
- [Add return_midpoint](https://github.com/p-j-smith/lipyphilic/commit/2882db5c6708ccb5a8bb3e0ed89af867c421dfdf) to `Zpositions` similar to `return_surface` from `MembThickness`.
- [Fix error with return_surface=True and n_bins=1](https://github.com/p-j-smith/lipyphilic/commit/6da77c181fda4f2c5151f8ef4c080530a83f9e5a)
PR Checklist
------------

Fixes #143, return_surface and return_midpoint
