docs/usage.rst

Fixes #
- 
PR Checklist
------------

sloppy mistakes

---

CHANGELOG.rst
docs/reference/analyses.rst
docs/reference/lib/registration.rst
src/lipyphilic/lib/registration.py
tests/lipyphilic/lib/test_registration.py
tox.ini

Fixes #5 
- Added a tool to calculate interleaflet registration
- Can calculate registration of lipid species using the `upper_sel` and `lower_sel` parameter
- Can calculate registration of lipids with specific user-defined values using the `filter_by` parameter
PR Checklist
------------

Registration analysis

---

src/lipyphilic/lib/registration.py

- Fix the formatting of maths in registration.py
- Fix the urls in  registration.py

More fixes for the docs

---

CHANGELOG.rst
README.rst
docs/installation.rst
docs/reference/analyses.rst
src/lipyphilic/lib/registration.py
tox.ini

Fixes #17 
- Better documentation
- Updated installation instructions to cover installation via conda-forge
- Info and examples of how to use each analysis tool
PR Checklist
------------

Better docs

---

CHANGELOG.rst
docs/reference/analyses.rst
docs/reference/lib/z_angles.rst
src/lipyphilic/lib/registration.py
src/lipyphilic/lib/z_angles.py
tests/lipyphilic/lib/test_z_angles.py

Fixes #20 
- Added a tool to calculate the angle between the `z`-axis and a vector made between two atoms in a lipid
PR Checklist
------------

Lipid orientation

---

CHANGELOG.rst
docs/reference/analyses.rst
docs/reference/lib/z_thickness.rst
src/lipyphilic/_simple_systems/pdbs/HexGrid-4AtomsPerLipid-Monolayer.pdb
src/lipyphilic/_simple_systems/simple_systems.py
src/lipyphilic/lib/area_per_lipid.py
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/flip_flop.py
src/lipyphilic/lib/neighbours.py
src/lipyphilic/lib/order_parameter.py
src/lipyphilic/lib/registration.py
src/lipyphilic/lib/z_angles.py
src/lipyphilic/lib/z_positions.py
src/lipyphilic/lib/z_thickness.py
tests/lipyphilic/lib/test_neighbours.py
tests/lipyphilic/lib/test_z_thickness.py

Fixes #25 
- Added a tool to calculate the thickness of lipids or their tails
- The output array can be passed directly to [Pomegranate](https://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html) for constructing a Hidden Markov Model to identify Lo and Ld tails
- Generally tidied up docs, especially the Analysis Tools section
PR Checklist
------------

Tail thickness

---

CHANGELOG.rst
docs/conf.py
docs/index.rst
docs/reference/analyses.rst
docs/reference/api.rst
docs/reference/lib/plotting.rst
requirements-dev.yml
requirements.yml
setup.py
src/lipyphilic/lib/plotting.py
src/lipyphilic/lib/z_angles.py
tests/lipyphilic/lib/test_plotting.py

Fixes #28 
- Added a tool to calculate joint probability densities
- Added a method to interpolate NaN values in the distribution
- Added a method to plot the density
- Optionally, the PMF of the two observable can be calculated from the probability distribution
- Added docs for the new plotting functionality
- Added and `Analysis API` section to the docs.
- Added tests for the new plotting module.
PR Checklist
------------

Plotting joint probability distributions

---

CHANGELOG.rst
docs/reference/analyses.rst
docs/usage.rst
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/order_parameter.py
src/lipyphilic/lib/plotting.py
src/lipyphilic/lib/z_angles.py
src/lipyphilic/lib/z_positions.py
src/lipyphilic/lib/z_thickness.py
tests/lipyphilic/lib/test_plotting.py

- Fix a bunch of typos in the docs
- Make "linear" the default method when interpolating with scipy.interpolate  as this is the default scipy method
- The `SCC` object returned by `SCC.weighted_average()` was missing some attributes
PR Checklist
------------

minor misc changes

---

CHANGELOG.rst
docs/reference/analyses.rst
docs/reference/api.rst
docs/reference/lib/memb_thickness.rst
src/lipyphilic/lib/assign_leaflets.py
src/lipyphilic/lib/flip_flop.py
src/lipyphilic/lib/memb_thickness.py
src/lipyphilic/lib/order_parameter.py
src/lipyphilic/lib/registration.py
src/lipyphilic/lib/z_thickness.py
tests/lipyphilic/lib/test_flip_flop.py
tests/lipyphilic/lib/test_memb_thickness.py

Fixes #34 
- Added a tool to calculate the bilayer thickness
- Optionally interpolates a high-resolution 2D grid of bilayer thicknesses
- Optionally returns the 2D grid for further analysis
PR Checklist
------------

Membrane thickness

---

docs/reference/analyses.rst
src/lipyphilic/lib/lateral_diffusion.py
src/lipyphilic/transformations.py

- Updated analysis example docs to reflect new `lipyphilic.lib.Neighbours` results structure
- Clarified purpose of `lipyphilic.transformations.center_membrane`
- Fixed other minor typos

Improve docs

---

src/lipyphilic/lib/assign_leaflets.py

- Tidy up class signatures for leaflet assignment

Tidy up class signatures for leaflet assignment

---

src/lipyphilic/transformations.py

- Update docs and comments for `lipyphilic.lib.transformations.center_membrane`
- Clarify how center_membrane works
PR Checklist
------------

Update docs for center_membrane

---

docs/index.rst
docs/reference/analyses.rst
docs/reference/api.rst
docs/reference/tutorials.rst
docs/usage.rst

Add better documentation of the interactive tutorials

Add doc page for interactive tutorials

---

pyproject.toml

Fixes #118 
- Add `attrs` as a dependency
PR Checklist
------------

Add attrs as a dependency

---

tests/lipyphilic/lib/test_memb_thickness.py

- Test thickness calculation on a non-uniform surface. This ensures we actually return a surface rather than a single value
PR Checklist
------------

Improve test for surface thickness calculation

---

CHANGELOG.rst

- make CHANGELOG up to date before new release
PR Checklist
------------

Update CHANGELOG before release

---

.github/workflows/publish.yml

- don't skip existing when uploading to PyPI
- skip existing when uploading to Test PyPI
PR Checklist
------------

skip existing when uploading to Test PyPI only

---

rust/Cargo.toml

- Set version to `0.11.0`
PR Checklist
------------

Release 0.11.0

---

.readthedocs.yml
README.rst
docs/Makefile
docs/conf.py

- only build html docs (no pdf, epub, htmlzip)
- fix url for test badge
PR Checklist
------------

Fix RTD docs build

---

.readthedocs.yml
docs/conf.py

- always use RTD theme when building docs
- also build epub and htmlzip formats
PR Checklist
------------

FIx RTD theme

---

.github/workflows/publish.yml

- update actions missed in #153 
PR Checklist
------------

Update `upload-artifact` and `download-artifact` actions

---

CHANGELOG.rst
rust/Cargo.toml

- Set version to 0.12.1
PR Checklist
------------

Release 0.12.1
